<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '6ba1ea4cc02f7c68e2cac30ba0b68025',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/rental',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_URL' => 'http://127.0.0.1:8000',
  'MAILER_DSN' => 'gmail+smtp://w311940@gmail.com:ptcxvfndosaxpwdc@default',
);
