<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_DEBUG' => '1',
  'APP_SECRET' => '6ba1ea4cc02f7c68e2cac30ba0b68025',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/rental',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_URL' => 'http://127.0.0.1:8000',
  'SMSGATEWAY_BASEURL' => 'wpm621.api.infobip.com',
  'SMSGATEWAY_APIKEYPREFIX' => 'App',
  'SMSGATEWAY_APIKEY' => 'fe3388f151981b54d31e2d7db2be8d27-4c8ba996-2137-4b49-844b-782bb8769182',
  'MAILER_DSN' => 'gmail+smtp://w311940@gmail.com:ptcxvfndosaxpwdc@default',
);
